module.exports = {
  test: {
    "CopyToChild*": "IEABCEFLJUAEF4SP",
    "Client*": "IEABCEFLJUAEF4AK",
    "Debtor*": "IEABCEFLJUAEGGC3",
    "Campaign Name*": "IEABCEFLJUAEF4AO",
    "URL*": "IEABCEFLJUAGLJUS",
    "Space Name*": "IEABCEFLJUAEF4SQ",
    "CampaignFeedbackStatus*": "IEABCEFLJUAGCXYP",
    "Feedback-Ref-ID": "IEABCEFLJUAGCSMH",
    "WrikeXPI-State": "IEABCEFLJUAGPAMB",
    "Agency*": "IEABCEFLJUAEF4AI",
    "Campaign Start Date*": "IEABCEFLJUAEF4BI",
    "Campaign End Date*": "IEABCEFLJUAEF4BJ",
    "Currency*": "IEABCEFLJUAEGPM6",
    "Campaign Objective*": "IEABCEFLJUAEF4B7",
    "Brand*": "IEABCEFLJUAEF4AJ",
    "Requestor's Market*": "IEABCEFLJUAEF4AM",
    "CCUID*": "IEABCEFLJUAGCS2I",
    "CSSID*": "IEABCEFLJUAGCS2J",
  },
  live: {
    "CopyToChild*": "IEAC7PRTJUADKV3A",
    "Client*": "IEAC7PRTJUAGPHMQ",
    "Debtor*": "IEAC7PRTJUAB72M2",
    "Campaign Name*": "IEAC7PRTJUAB43EK",
    "URL*": "IEAC7PRTJUADKX7R",
    "Space Name*": "IEAC7PRTJUADKWAW",
    "CampaignFeedbackStatus*": "IEAC7PRTJUAEGVJ6",
    "Feedback-Ref-ID": "IEAC7PRTJUAEGKBO",
    "WrikeXPI-State": "IEAC7PRTJUAGPA6B",
    "Agency*": "IEAC7PRTJUAB43DB",
    "Campaign Start Date*": "IEAC7PRTJUAB5IHK",
    "Campaign End Date*": "IEAC7PRTJUAB5IHL",
    "Currency*": "IEAC7PRTJUAB5BLC",
    "Campaign Objective*": "IEAC7PRTJUAB7P4W",
    "Brand*": "IEAC7PRTJUAB43DE",
    "Requestor's Market*": "IEAC7PRTJUAB43DP",
    "CCUID*": "IEAC7PRTJUAEF7QO",
    "CSSID*": "IEAC7PRTJUAEGSYH",
  },
};
