module.exports = {
  test: {
    "CopyToChild*": "IEABCEFLJUAEF4SP",
    "Client*": "IEABCEFLJUAEF4AK",
    "Debtor*": "IEABCEFLJUAEGGC3",
    "Campaign Name*": "IEABCEFLJUAEF4AO",
    "URL*": "IEABCEFLJUAGLJUS",
    "Space Name*": "IEABCEFLJUAEF4SQ",
    "CampaignFeedbackStatus*": "IEABCEFLJUAGCXYP",
    "Feedback-Ref-ID": "IEABCEFLJUAGCSMH",
    "WrikeXPI-State": "IEABCEFLJUAGPAMB",
    "Agency*": "IEABCEFLJUAEF4AI",
    "Campaign Start Date*": "IEABCEFLJUAEF4BI",
    "Campaign End Date*": "IEABCEFLJUAEF4BJ",
    "Currency*": "IEABCEFLJUAEGPM6",
    "Campaign Objective*": "IEABCEFLJUAEF4B7",
    "Brand*": "IEABCEFLJUAEF4AJ",
    "Requestor's Market*": "IEABCEFLJUAEF4AM",
    "CCUID*": "IEABCEFLJUAGCS2I",
    "CSSID*": "IEABCEFLJUAGCS2J",
  },
  live: {
    "CopyToChild*": "IEAC7PRTJUADKV3A",
    "Agency*": "IEAC7PRTJUAB43DB",
    "Client*": "IEAC7PRTJUAGPHMQ",
    "Debtor*": "",
    "Campaign Name*": "",
    "URL*": "",
    "Space Name*": "",
    "CampaignFeedbackStatus*": "",
    "Feedback-Ref-ID": "",
    "WrikeXPI-State": "",
    "Campaign Start Date*": "",
    "Campaign End Date*": "",
    "Currency*": "",
    "Campaign Objective*": "",
    "Brand*": "",
    "Requestor's Market*": "",
    "CCUID*": "",
    "CSSID*": "",
  },
};
